### ISSUE TITLE
Soportar entry_date con tiempo

### ISSUE THREAD

**Issue by dacasas** [platanus/ledgerizer#15]
En la creación de movimientos (execute_movement_entry) cuando se ingresa el entry date, este trunca el tiempo a 00:00.
Esto hace que al momento de filtrar para obtener el balance o las ledger_lines, sea un poco confuso, ya que no se pueden retornar solo algunos movimientos de un día. O están todos, o no está ninguno.
En resumen, sería bueno poder filtrar por hora.

**Comment by ldlsegovia** [comment]
done
